name: Build & Publish

on:
  push:
    tags:
      - v*.*.*

env:
  JAVA_VERSION: 21
  BUILD_RELEASE: "true"
  GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}
  MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
  CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}


permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build and Publish
        run: ./gradlew clean buildAndGather publish

      - name: Publish
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          github-token: "${{env.GITHUB_TOKEN}}"
