name: Build & Publish

on:
  push:
    tags:
      - v*.*.*

env:
  JAVA_VERSION: 21
  BUILD_RELEASE: "true"
  CURSEFORGE_TOKEN: "32043cd4-ecfc-4161-8308-d39defe914cf"
  MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}


permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build and Publish
        run: ./gradlew clean buildAndGather publishAll --warning-mode all --stacktrace

      - name: Publish to Github
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          github-token: "${{secrets.GITHUB_TOKEN}}"
